#!/bin/bash

set -eux

SO_NAME=bin/libmalloc-opt.so

support/gen-makefile.py
make ${SO_NAME}

ulimit -c unlimited  # allow core file to be written
rm -f core  # remove previous if any

export LD_PRELOAD=`pwd`/${SO_NAME}

time $@
