#!/bin/bash

set -eux

mkdir -p bin

cc -std=gnu99 -Wall -Werror -g -shared -fPIC -DEXPORT_REAL_API -I include \
    -o bin/malloc.so src/*

export LD_PRELOAD=`pwd`/bin/malloc.so

ulimit -c unlimited

$@