#!/bin/bash

set -eux

support/gen-makefile.py
make build-shared-libraries

ulimit -c unlimited  # allow core file to be written
rm -f core  # remove previous if any

export LD_PRELOAD=`pwd`/bin/libmalloc.so

$@
